server:
  port: 8092

spring:
    redis:
      host: r-2ze1711570d62204.redis.rds.aliyuncs.com
      port: 6379
      database: 10
      timeout: 3000
      password: Longbei2015
      jedis:
        pool:
          max-active: 1024  #最大连接数
          max-wait: 20000  #连接池最大等待时间
          max-idle: 200  #最大空闲

    kafka:
      bootstrap-servers: 192.168.1.18:9092,192.168.1.19:9092,192.168.1.20:9092
      producer:
          # 重试次数
          retries: 3
          # 批量发送的消息数量
          batch-size: 16384
          # 32MB的批处理缓冲区
          buffer-memory: 33554432
      consumer:
          # 默认消费者组
          group-id: longbei
          # 最早未被消费的offset
          auto-offset-reset: earliest     #latest 如果有已提交的offset从已提交的开始消费，没有则从新消息开始消费
          # 批量一次最大拉取数据量
          max-poll-records: 1000
          # 自动提交
          auto-commit-interval: 1000
          enable-auto-commit: false
          key-deserializer: com.alibaba.otter.canal.client.kafka.MessageDeserializer
          value-deserializer: com.alibaba.otter.canal.client.kafka.MessageDeserializer

logging:
  config: classpath:logback.xml

topicName:
    topic1: order.student
    topic2: order.product



#    redis:
#      password: 123456
#      sentinel:
#        master: mymaster
#        nodes: 192.168.1.19:26379,192.168.1.20:26379,192.168.1.21:26379
#      timeout: 6000ms
#      jedis:
#        pool:
#          max-active: 1024  #最大连接数
#          max-wait: 20000  #连接池最大等待时间
#          max-idle: 200  #最大空闲